# Generated by Django 2.1.2 on 2018-10-24 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=64)),
                ('add_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_number', models.AutoField(primary_key=True, serialize=False, verbose_name='员工号')),
                ('employee_name', models.CharField(editable=False, max_length=30, verbose_name='姓名')),
                ('integration', models.IntegerField(default='0', verbose_name='持有积分')),
                ('discount', models.FloatField(default='1', verbose_name='享有折扣')),
                ('vip_Flag', models.BooleanField(default=False, editable=False, verbose_name='会员标志')),
            ],
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('goods_number', models.AutoField(primary_key=True, serialize=False, verbose_name='商品号')),
                ('goods_name', models.CharField(editable=False, max_length=100, verbose_name='商品名')),
                ('goods_value', models.IntegerField(default='0', verbose_name='人名币价值')),
                ('goods_integration', models.IntegerField(default='0', verbose_name='积分价值')),
                ('goods_repertory', models.IntegerField(default='0', verbose_name='商品库存')),
                ('day_conversion_max', models.IntegerField(default='0', verbose_name='每日兑换上限')),
                ('goods_img', models.ImageField(upload_to='img', verbose_name='商品图片')),
                ('goods_describe', models.CharField(max_length=1000, verbose_name='商品描述')),
                ('goods_end_date', models.DateField(blank=True, default=None, null=True, verbose_name='商品结束兑换日期')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(max_length=254)),
                ('message', models.CharField(max_length=255)),
                ('msg_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('msg_remark', models.CharField(max_length=255)),
                ('deal_remark', models.CharField(max_length=255)),
                ('deal_flag', models.CharField(default='0', max_length=2)),
                ('deal_date', models.DateTimeField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='a', max_length=20)),
                ('age', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=64)),
                ('password', models.CharField(max_length=64)),
                ('user_email', models.EmailField(max_length=254)),
                ('user_phone', models.CharField(default=' ', max_length=18)),
            ],
        ),
    ]
