# Generated by Django 2.1.2 on 2018-10-11 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='age',
            field=models.IntegerField(null=True),
        ),
    ]
