# Generated by Django 2.1.2 on 2018-10-24 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(editable=False, max_length=30, verbose_name='流水号')),
                ('order_remark', models.CharField(max_length=50, verbose_name='流水备注')),
                ('order_date', models.DateField(blank=True, default=None, null=True, verbose_name='兑换日期')),
                ('order_amount', models.IntegerField(default='1', verbose_name='兑换数量')),
                ('order_integration', models.IntegerField(default='0', verbose_name='扣除积分')),
                ('order_state', models.CharField(default='0', max_length=2, verbose_name='流水状态')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Employee')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Goods')),
            ],
        ),
    ]
