# Generated by Django 2.1.2 on 2018-10-25 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='goods_describe',
            field=models.CharField(default='null', max_length=1000, verbose_name='商品描述'),
        ),
    ]
