# Generated by Django 2.1.2 on 2018-10-16 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_phone',
            field=models.CharField(default=' ', max_length=18),
        ),
    ]
