# Generated by Django 2.1.2 on 2018-10-16 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_user_user_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_pwd',
            new_name='password',
        ),
    ]
