# Generated by Django 2.1.2 on 2018-10-17 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_auto_20181016_1731'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(max_length=254)),
                ('message', models.CharField(max_length=255)),
                ('msg_date', models.DateTimeField()),
                ('msg_remark', models.CharField(max_length=255)),
                ('deal_remark', models.CharField(max_length=255)),
                ('deal_flag', models.CharField(default='0', max_length=2)),
                ('deal_date', models.DateTimeField()),
            ],
        ),
    ]
